extends:
  - plugin:@typescript-eslint/recommended
  - prettier
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - simple-import-sort
root: true
rules:
  "@typescript-eslint/no-explicit-any": 0
  simple-import-sort/imports: error
  simple-import-sort/exports: error
